### ISSUE TITLE
Missing coding style

### ISSUE THREAD

**Issue by peter279k** [doganoo/PHPUtil#1]
As title, I'm confused about this package coding style.

After looking at source code of package, it seems that this package doesn't allow the [PSR-2 coding style](https://www.php-fig.org/psr/psr-2/).

@doganoo, which coding style we use on this package?

We can also consider integrating the coding style to help us to fix/check coding style easily :).

**Comment by doganoo** [comment]
Hey @peter279k 

sorry, I have seen your comment very late! :)

This repo is a personal collection of various stuff that I use daily here und there. I would not say it is a project. When I see some classes and components have potential, I exclude them from PHPUtil and create a seperate repository.

But, if you want to follow a code style or want to introduce it to PHPUtil - feel free :)
